spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lgp
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mappers/*.xml

logging:
  level:
    org:
      mybatis: DEBUG
      lgp:
        mapper: DEBUG